### ISSUE TITLE
 Cannot link to /mysql, as it does not belong to the default network.

### ISSUE THREAD

**Issue by makorne** [confirm/docker-mysql-backup#13] opened 2018-03-20 17:14 UTC
docker network create my-net
docker run --network my-net --name mysql -d mysql

docker run --name backup --link mysql -v /backup:/backup confirm/mysql-backup
```
Status: Downloaded newer image for confirm/mysql-backup:latest
docker: Error response from daemon: Cannot link to /mysql, as it does not belong to the default network.
ERRO[0016] error waiting for container: context canceled 
```
docker run --name backup --network my-net --link mysql -v /backup:/backup confirm/mysql-backup
```
ERROR: Couldn't find linked MySQL container.
Please link a MySQL or MariaDB container to the backup container and try again
```

**Comment by crizbe** [comment] 2018-10-17 13:11
Hi makorne,
I run into the same error as you do.
Did you find a solution?

Regards cbxxn

**Comment by silviotroia** [comment] 2019-04-13 08:54
+1

**Comment by STX2k** [comment] 2019-04-22 15:15
+1

**Comment by eclimov** [comment] 2019-05-06 16:47
+1

**Comment by domibarton** [comment] 2019-05-16 09:28
Sorry I no longer use the container/image myself, thus supporting it is challening ;) I've to setup everything again to see how newer Docker versions work, especially with sharing the env vars.

In the meantime, did anyone try to fix or find the problem or was `+1` the only effort in "supporting" open source? 😬

**Comment by domibarton** [comment] 2019-05-16 09:40
Closing this issue in favor #2, which is the root cause for the `ERROR: Couldn't find linked MySQL container.` error. 

Regarding the network error: This is a "Docker" thing and everyone using Docker should be aware of it. IMHO it doesn't make any sense to repeatedly document this in every docker image / container using links. However, a note could be helpful in the docs :)

**Closed as completed by domibarton** 2019-05-16 09:40 UTC

**Comment by limbuu** [comment] 2019-06-17 18:12
you just need to add --network my-net in second line as well i.e 
docker network create my-net
docker run --network my-net --name mysql -d mysql
docker run --network my-net --name backup --link mysql -v /backup:/backup confirm/mysql-backup

It is necessary to run all containers you want to link within same network.
